def univ_data():
    uni_data = [
        {"Stanford University": 5},
        {"Carnegie Mellon University": 5},
        {"St. Louis University": 5},
        {"Harvard University": 5},
        {"Trinity College, Dublin": 5},
        {"Waterloo University": 5},
        {"Massachusetts Institute of Technology": 5},
        {"University of California, Berkeley": 5},
        {"University of California, San Diego": 4},
        {"Purdue University, West Lafayette": 4},
        {"University of Illinois, Urbana Champaigne": 4},
        {"Cornell University": 4},
        {"University of British Columbia": 4},
        {"University of Washington": 4},
        {"Georgia Tech University": 4},
        {"University of Texas, Dallas": 4},
        {"New York University": 3},
        {"Ohio State University": 3},
        {"Pennsylvania State University": 3},
        {"Stony Brook University--SUNY": 3},
        {"University of Florida": 3},
        {"Glasgow University": 3},
        {"Northeastern University": 2},
        {"University of Notre Dame": 2},
        {"University of Pittsburgh": 2},
        {"Universtity of Rochester": 2},
        {"Michigan State University": 2},
        {"Illinois Institute of Technology": 1},
        {"University of Kansas": 1},
        {"Universty of Kentucky": 1},
        {"West Virginia University": 1},
        {"University of Maine": 1},
        {"University of Idaho": 1},
        {"Montana State University": 1},
        {"North Dakota State University": 1}
    ]
    return uni_data
